### ISSUE TITLE
[Suggestion] Remove "Image" button

### ISSUE THREAD

**Issue by Imerion** [robiso/summernote-editor#13]
Since the new "Picture"-button both has an option to insert an image from a link as well as upload from a computer, is there a need for the "Image" button which only adds an image using a link? If not, how about removing the "Image" button as to not confuse users.

**Comment by robiso** [comment]
@Imerion it seems to make sense after a quick test, this has been removed with the new 3.4.0 version. 
This new update also includes image compression from 10MB and to 1920(full hd) resolutions while drag and dropping files.

If you want to join our list of contributors: https://www.wondercms.com/contributors
Please list your first/last name and website. :) 

Thank you!

**Comment by Imerion** [comment]
Awesome, thanks again for continuing to improve this great CMS! Image compression is great to have too!

No need to add me to the list for this. (I think I might already be listed though, due to the Swedish translation I made and should probably update some day.) :)

**Comment by robiso** [comment]
@Imerion can you double check if you're on the list please, we love including contributors, sometimes we lose track record and might ask twice :)

Thank you for your amazing support!

**Comment by Imerion** [comment]
@robiso Just checked, I'm on the list. Thanks for asking though, I"d really like to help out more!

And thanks to you for your amazing work on this!

**Comment by robiso** [comment]
Thank you for checking @Imerion!

Feel free to contribute in any way you feel comfortable, the most available is the issues section on GitHub and helping out users in our community, but your support is already more than enough. 🙂

Looking forward to many more years of maintaining this little project and steadily growing our userbase with wholesome supporters like yourself. 

Have a healthy, successful 2023. All the best to you and your loved ones.  🍻

Edit: whoops accidentally reopened issue, closing again :)
