### ISSUE TITLE
Plugin indicates a misconfiguration.

### ISSUE THREAD

**Issue by TechArea** [robiso/summernote-editor#4]
Notice: Constant version already defined in /home/techarea/public_html/plugins/summernote-editor/summernote-editor.php on line 15

[https://i.postimg.cc/mkH05XfB/Screenshot-2020-05-17-at-12-27-47.png](https://i.postimg.cc/mkH05XfB/Screenshot-2020-05-17-at-12-27-47.png)

**Comment by robiso** [comment]
@TechArea update pushed out. Thanks for reporting! 🚀 
Let me know if the latest 3.0.8 version fixes it for you.

**Comment by TechArea** [comment]
fixed :-)
