### ISSUE TITLE
Missing "New Editable Area"

### ISSUE THREAD

**Issue by NorfolkGreg** [robiso/summernote-editor#5]
I'm new to Github, so may be missing something or not following protocol, so please forgive me.

The WonderCMS Demo has Summernote 3.0.8 installed and it shows an "Add New Editable Area" button under the currently edited area. I have just installed 3.1.1 to my newly installation of WonderCMS. It lacks that facility. Has it gone missing in the upgrade or do I have to edit a setting somewhere to add it?

**Comment by NorfolkGreg** [comment]
Oops! Disregard!
Discovered that it is provided by the "Additional Content" plugin (though the README.md file there appears a little out of date.)

**Comment by robiso** [comment]
@NorfolkGreg sorry for the late response.
We updated the screenshot for summernote in case that was causing confusion.

Which ReadME file seems outdated, the Additional contents or the Summernote? If it causes confusion we'll fix it :)
