### ISSUE TITLE
Invisible Link Address

### ISSUE THREAD

**Issue by NorfolkGreg** [robiso/summernote-editor#6]
When editing a link address within the pop-up box it is often impossible to read it because the text colour is driven by the currently active theme. Is it possible to fix the colour to black as the background always been white with the themes I have tested?

**Comment by NorfolkGreg** [comment]
That's what comes of being new to the editor!
I now see that one doesn't edit that invisible text, it simply shows the link address rather than the link text. Once you click the Edit button a very workable dialogue appears. Nevertheless it would still be good to have the link address visible without having to open the editor dialogue.

**Comment by robiso** [comment]
This should be now improved in the latest version :)
